compare_recon_to_gt:
  _target_: src.callbacks.compare_reconstruction_to_gt.CompareReconstructionToGT
  patch_dir: null # Location of the patch, to be set after overwriting data.hdf5_dir (in experiment config)
  log_every_n_epochs: 5
  blend_profile: "sigmoid"
  overlap: 16
  verbose: False
