# @package _global_

defaults:
  - data: tsx_ssc # choose datamodule with `test_dataloader()` for evaluation
  - model: sar_hyperprior
  - logger: wandb
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - _self_

# @TODO: Modify the task-name behavior so that by default, when evaluating a model, the task name is set to "eval/<dataset>/<model>" without having to duplicate the experiment config file
task_name: "eval"
tags: ["sar_hyperprior", "tsx_ssc"]

data:
  hdf5_dir: ${paths.data_dir}processed_hdf5/spatialsplit5_nopres_norm0nat
  log_mode: "natural"
  must_normalize: null # 0 <=> true min-max, 1 <=> min-max with 1% and 99% percentiles, etc.
  batch_size: 16
  num_workers: 11

model:
  criterion:
    metric: "merlin" # "mse" or "ssim" or "ms_ssim"
    lmbda: 25
  net_optimizer:
    lr: 1e-5 # Got infinite loss with 0.001

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
